#goal to deploy the build and tested image to an ec2 instance 

name: CD
on:
  workflow_dispatch:
jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
     - name: code checkout
       uses: actions/checkout@v7

       
     -   name: run docker container
         run:  docker compose -f docker.compose.yml up -d
