#Goal: to build and push docker image 
 name: Docker build and push 
 on: 
   push:
 jobs: 
   build-and-push:
      runs-on: ubuntu-latest
      steps:
          - name: checkout code 
            uses: actions/checkout@v7

          - name: Docker Login
            env:
             DOCKER_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
             DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
             run: |
              echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
          